---
# need for docker build
sudo: true
dist: bionic
addons:
  apt:
    packages:
      - coreutils
      - ruby
      - socat
services:
  - docker

language: go
branches:
  only:
    - master

go: 1.13.x

env:
  global:
    - CEPH_CSI_RUN_ALL_TESTS=true

before_install:
  - mkdir -p $GOPATH/bin

before_script:
  - curl https://download.ceph.com/keys/release.asc | sudo apt-key add -
  - sudo apt-add-repository
    "deb https://download.ceph.com/debian-nautilus $(lsb_release -sc) main"
  # Ceph does not guarantee arm64 builds, fallback to ceph 14.2.5
  # yamllint disable rule:line-length
  - test "$(arch)" != "aarch64" || sudo apt-add-repository
    "deb https://chacra.ceph.com/r/ceph/nautilus/af06652dc9b2da8c6aadbbecdfafdc7e235abe7d/ubuntu/xenial/flavors/default/ xenial main"
  # yamllint enable rule:line-length
  - sudo apt-get -qq update
  # only the arm64 fallback repo is unsigned and needs --allow-unauthenticated
  - sudo apt-get -y --allow-unauthenticated install librados-dev librbd-dev

# Two stages for testing, each stage runs its jobs in parallel, but stages are
# run after each other, unless the last stage fails.
# Only run the deploy stage on push (not pull_request) events.
stages:
  - build testing
  - e2e testing
  - name: deploy
    if: type = push

jobs:
  include:
    - stage: build testing
      name: cephcsi on Arm64
      dist: xenial   # There are no arm64 builds available in bionic repo
      arch: arm64
      script:
        - scripts/skip-doc-change.sh || travis_terminate 0;
        - make image-cephcsi || travis_terminate 1;
        # No CI test job is availabe for Arm64 now due to below issues
        # - k8s-csi sidecar images for Arm64 are not available
        # - Travis Arm64 CI job runs inside unprivileged LXD which blocks
        #   launching minikube test environment
        - travis_terminate 0    # deploy only on x86
    - stage: build testing
      name: cephcsi on Amd64
      dist: xenial   # There are no arm64 builds available in bionic repo
      arch: amd64
      script:
        - scripts/skip-doc-change.sh || travis_terminate 0;
        - make image-cephcsi || travis_terminate 1;
        # No CI test job is availabe for Arm64 now due to below issues
        # - k8s-csi sidecar images for Arm64 are not available
        # - Travis Arm64 CI job runs inside unprivileged LXD which blocks
        #   launching minikube test environment
        - travis_terminate 0    # deploy only on x86
